- type: job
  parent: AU14JobLEOBase
  id: AU14JobForeignMobGoonJob
  roundSide: ThirdParty
  roundForce: CRIMINAL
  roundRole: ForeignMobGoonJob
  roundComponents:
  - type: Skills
    skills:
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
      RMCSkillFirearms: 2
  - type: JobPrefix
    prefix: au14-job-prefix-mobboss
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: synth
  - type: FactionLanguageMember
    factionTag: ForeignMob

  name: au14-job-name-mobgoon
  description: "Вас із вашим босом вигнали зі старої території, і ви втратили все. Але старі звички не зникають: переселіться на територію суперників і почніть заново."
  setPreference: false
  playTimeTracker: AU14JobMobGoon
  startingGear: AU14GearForeignMobGoonGear
  icon: "AU14JobIconColonyMobGoon"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-mobgoon
  spawnMenuRoleName: Mob Goon (3rd party)
  accessGroups:
  - Colonist
  roleWeight: 0.25
  ranks:
    RMCRankCivilian: []
  hidden: false

- type: entity
  parent: AU14BaseMobSpeciesOrganicMisc
  id: AU14JobForeignMobGoon
  name: "Бандит мафії (злочинець)"
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: Mob Boss (Criminal)
    description: "Вас із вашим босом вигнали зі старої території, і ви втратили все. Але старі звички не зникають: переселіться на територію суперників і почніть заново."
    reregister: false
    job: AU14JobForeignMobGoonJob
    raffle:
      settings: short
    rules: You do not know what is going on in the colony.

- type: startingGear
  id: AU14GearForeignMobGoonGear
  equipment:
    jumpsuit: CMJumpsuitLiaisonCharcoal
    shoes: RMCShoesLaceup
    id: AU14IDCardMobGoon
    back: CMSatchel
