- type: loadoutGroup
  id: SynthUniformAU14
  name: rmc-loadout-group-synthetic-uniform
  minLimit: 1
  loadouts:
  - CivilianBoilerSuitDarkBlueSynthAU14
  - SynthUniformRMC
  - SynthJumpsuitPristineRMC
  - ScrubsBlueRMC
  - ScrubsLightBlueRMC
  - ScrubsGreenRMC
  - ScrubsPurpleRMC
  - ScrubsOliveRMC
  - ScrubsGreyRMC
  - EngineerUniformRMC
  - MPUniformRMC
  - TShirtWhiteRMC
  - TShirtGrayRMC
  - TShirtRedRMC
  - CivilianJumpsuitRMC
  - WhiteServiceJumpsuitRMC
  - LiaisonBlueJumpsuitRMC
  - LiaisonBrownJumpsuitRMC
  - LiaisonCorporateFormalJumpsuitRMC
