- type: entity
  id: AU14LanguagePresetICSC
  name: "Мови ICSC"
  categories: [ HideSpawnMenu ]
  components:
  - type: LanguagePreset
    spokenLanguages:
    - French
    - English
    - Turkish
    - Korean
    understoodLanguages:
    - French
    - English
    - Turkish
    - Korean
    currentLanguage: French
    defaultLanguage: French
