- type: entity
  id: AU14LanguagePresetTWE
  name: "Мови TWE"
  categories: [ HideSpawnMenu ]
  components:
  - type: LanguagePreset
    spokenLanguages:
    - English
    - Japanese
    understoodLanguages:
    - English
    - Japanese
    currentLanguage: English
    defaultLanguage: English
