- type: entity
  id: AU14LanguagePresetUPPEnlisted
  name: UPP enlisted Languages
  categories: [ HideSpawnMenu ]
  components:
  - type: LanguagePreset
    spokenLanguages:
    - Russian
    - German
    - Chinese
    - Spanish
    understoodLanguages:
    - Russian
    - German
    - Chinese
    - Spanish
    currentLanguage: German
    defaultLanguage: German

- type: entity
  id: AU14LanguagePresetUPPOfficer
  name: UPP officer Languages
  categories: [ HideSpawnMenu ]
  components:
  - type: LanguagePreset
    spokenLanguages:
    - English
    - Russian
    - German
    - Chinese
    - Spanish
    understoodLanguages:
    - English
    - Russian
    - German
    - Chinese
    - Spanish
    currentLanguage: German
    defaultLanguage: German