- type: job
  parent: CMJobBase
  id: AU14Jobk9handlerBase
  name: "Кінолог К9"
  description: "Кінолог К9"
  setPreference: false
  playTimeTracker: AU14JobThirdPartyK9Handler
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobThirdPartyK9Handler
  isHumanoid: true
