- type: roleLoadout
  id: JobJobAU14JobMilitaryDoctorBase
  points: 7
  groups:
  - GOVFORDoctorEquipmentAU14
  - GOVFORDoctorUniformAU14
  - MedJacketMilitaryAU14
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobadvisorBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - WeaponsRMC

- type: roleLoadout
  id: JobAU14JobPlatCoBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - GOVFORPlatCOSidearmBeltAU14

- type: roleLoadout
  id: JobAU14JobPlatoonCorpsmanBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobDCCBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobPlatOpBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - WeaponsRMC

- type: roleLoadout
  id: JobAU14JobDSPilotBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - WeaponsRMC

- type: roleLoadout
  id: JobAU14JobRadioTelephoneOperatorBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobSectionSergeantBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobSquadAutomaticRiflemanBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobSquadCombatTechBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobSquadRiflemanBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMC
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobSquadSergeantBase
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - WeaponsRMC

- type: roleLoadout
  id: JobAU14JobAuxSupportSynthBase
  points: 7
  groups:
  - GOVFORSynthSpecializationAU14
  - SynthBackpackAU14
  - SynthBeltAU14
  - SynthPouchesLeftAU14
  - SynthPouchesRightAU14
  - SynthGlovesAU14
  - SynthHeadwearAU14
  - SynthGlassesAU14
  - SynthUniformAU14
  - SynthUniformAccessoriesRMC
  - SynthSuitAU14
  - SynthSuitSpecialAU14
  - SynthEquipmentAU14
  - SynthShoesRMC
  - SynthMasksAU14
  - PaperworkRMC
  - RecreationalRMC
  - HelmetGarbsRMC
  - SmokablesRMC
  - ForceStampApprovedAU14
  - ForceSynthResetKeyAU14
  - SynthAccesoriesSpecialAU14

- type: roleLoadout
  id: JobAU14JobAuxTechBase
  points: 7
  groups:
  - GOVFORAuxTechClothingAU14
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
