# base
- type: entity
  parent: RMCArmbandBase
  id: AU14ChevronPrDBase
  abstract: true
  suffix: PSC Rank Chevron
  description: "Відзнака звання підрозділу реагування приватного охоронного підрядника. Надрукована на 3D-принтері, із залишками ламінату та затискачем-«крокодилом» для кріплення до лацкана. Як завжди, несмак."

# ├──[ Platoon Ranks ]───────────────────────────────────────────────┤

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDRecruit
  name: "шеврон стажера підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_enlisted
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_enlisted
  - type: RankChanger
    rank: AU14RankPrDRecruit
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDAssociate
  name: "шеврон помічника підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_enlisted
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_enlisted
  - type: RankChanger
    rank: AU14RankPrDAssociate
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDOperator
  name: "шеврон оператора підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_enlisted
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_enlisted
  - type: RankChanger
    rank: AU14RankPrDOperator
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDSeniorOperator
  name: "шеврон старшого оператора"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_enlisted
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_enlisted
  - type: RankChanger
    rank: AU14RankPrDSeniorOperator
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDEnforcer
  name: "шеврон енфорсера підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_nco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_nco
  - type: RankChanger
    rank: AU14RankPrDEnforcer
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDEnforcerSenior
  name: "шеврон старшого енфорсера підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_nco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_nco
  - type: RankChanger
    rank: AU14RankPrDEnforcerSenior
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDEnforcerLead
  name: "шеврон провідного енфорсера підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_snco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_snco
  - type: RankChanger
    rank: AU14RankPrDEnforcerLead
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDAdjutant
  name: "шеврон ад'ютанта підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: AU14RankPrDAdjutant
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDCommander
  name: "шеврон командира підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: AU14RankPrDCommander
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDCommanderSenior
  name: "шеврон старшого командира підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: AU14RankPrDCommanderSenior
    override: true

# ├──[ Synthetic ]────────────────────────────────────────────────────┤

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDSynth1
  name: "шеврон синтетика підрозділу реагування класу 1"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_warrant
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_warrant
  - type: RankChanger
    rank: AU14RankPrDSynth1
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDSynth2
  name: "шеврон синтетика підрозділу реагування класу 2"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_warrant
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_warrant
  - type: RankChanger
    rank: AU14RankPrDSynth2
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDSynth3
  name: "шеврон синтетика підрозділу реагування класу 3"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_warrant
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_warrant
  - type: RankChanger
    rank: AU14RankPrDSynth3
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDSynth4
  name: "шеврон синтетика підрозділу реагування класу 4"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_warrant
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_warrant
  - type: RankChanger
    rank: AU14RankPrDSynth4
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDSynth5
  name: "шеврон синтетика підрозділу реагування класу 5"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_warrant
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_warrant
  - type: RankChanger
    rank: AU14RankPrDSynth5
    override: true

# ├──[ Aviation ]─────────────────────────────────────────────────────┤

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDPilot
  name: "шеврон пілота підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: AU14RankPrDPilot
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDSeniorPilot
  name: "шеврон старшого пілота підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: AU14RankPrDSeniorPilot
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDCrewChief
  name: "шеврон командира екіпажу підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_snco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_snco
  - type: RankChanger
    rank: AU14RankPrDCrewChief
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDSeniorCrewChief
  name: "шеврон старшого командира екіпажу підрозділу реагування"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_snco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_snco
  - type: RankChanger
    rank: AU14RankPrDSeniorCrewChief
    override: true

# ├──[ Command ]──────────────────────────────────────────────────────┤

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDDeputyDirector
  name: "шеврон заступника директора з операцій"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_flagofficer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_flagofficer
  - type: RankChanger
    rank: AU14RankPrDDeputyDirector
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDOperationsDirector
  name: "шеврон директора з операцій"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_flagofficer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_flagofficer
  - type: RankChanger
    rank: AU14RankPrDOperationsDirector
    override: true

- type: entity
  parent: AU14ChevronPrDBase
  id: AU14ChevronPrDRegionDirector
  name: "шеврон регіонального директора"
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_flagofficer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_flagofficer
  - type: RankChanger
    rank: AU14RankPrDRegionDirector
    override: true