- type: entity
  id: AU14SkillPresetMilitaryDoctor
  name: Military Doctor
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillOverwatch: 1
      RMCSkillLeadership: 1
      RMCSkillIntel: 1
      RMCSkillMedical: 4
      RMCSkillSurgery: 4
      RMCSkillPolice: 1
