- type: entity
  id: AU14SkillPresetPlatoonRTO
  name: Radio Traffic Operator
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillLeadership: 1
      RMCSkillJtac: 4
      RMCSkillFirearms: 1
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillConstruction: 2
      RMCSkillEngineer: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
